inherit_from: .rubocop_todo.yml
require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Include:
    - '**/Rakefile'
  Exclude:
    - '.internal_test_app/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 185
